### ISSUE TITLE
Upgrade to PHP 8.1 and Guzzle 8

### ISSUE THREAD

**Issue by oakleaf** [dimafe6/bank-id#15]
Hello, how far away are we from having this lib work with php 8.1 a later guzzle version than 7?

**Comment by dimafe6** [comment]
for now i cannot continue work on this lib due to russia attack on Ukraine. after Ukraine win i will continue. 🇺🇦
You can support Ukrainian army. Thanks.
https://bank.gov.ua/en/news/all/natsionalniy-bank-vidkriv-spetsrahunok-dlya-zboru-koshtiv-na-potrebi-armiyi
