### ISSUE TITLE
BankID API v5

### ISSUE THREAD

**Issue by puggan** [dimafe6/bank-id#2]
Version 5 of the API is a JSON REST API.
And also support the cancel-command.

Have a working version at:
https://github.com/puggan/bank-id

But have no good idea how to merge them without breaking the current implementations.

**Comment by dimafe6** [comment]
Hi. Thanks for the issue. I will work on the development of version 5 in the near future

**Comment by dimafe6** [comment]
Creating version [2.0.0](https://github.com/dimafe6/bank-id/releases/tag/2.0.0) for BankID API V5
