### ISSUE TITLE
 "personalNumber" should be optional while authenticating

### ISSUE THREAD

**Issue by oakleaf** [dimafe6/bank-id#6]
#58 in BankIDService.php; "personalNumber" is optional while authenticating. This relies on paragraph "14.1.1 Parameters for auth and sign" from https://www.bankid.com/assets/bankid/rp/bankid-relying-party-guidelines-v3.2.2.pdf.

Suggestion; Just check if the $personalNumber not is null, if not, include it in the parameters.

**Comment by Livijn** [comment]
Why did you close this? It makes sense.

**Comment by Livijn** [comment]
Should be closed since this was actually added in #5
