### ISSUE TITLE
Update repository to 2.0.1 latest version?

### ISSUE THREAD

**Issue by oakleaf** [dimafe6/bank-id#9]
Hello and thank you for a great repository, but Im having problem not being able to download the latest code that includes the optional use of PersonNumber when using "getAuthResponse". When I try to use dev-master or 2.0.0 im still getting the old codes from 1.0 (From what I can see).

**Comment by dimafe6** [comment]
You are using the composer to install this library?

**Comment by dimafe6** [comment]
Try to use the dev-master version. 
`composer require dimafe6/bank-id:dev-master`

**Comment by oakleaf** [comment]
Yes exactly, now it seems to work
